config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Loan
  get '/loan/new', to: 'loan#new'
  post '/loan/new', to: 'loan#create'

  # Item
  get '/item/new', to: 'item#new'
  post '/item/new', to: 'item#create'

  root 'loan#index'
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/item_controller.rb
class ItemController < ApplicationController

  before_action :parse_params

  def new
  end

  def create
    puts params.to_json

  end

  private

  def parse_params
    @total = params[:to_ids].map { |e| e.split(',')[1].to_i }.sum
  end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/item/new.html.erb
<%= form_tag item_new_path do %>
  <%= select_tag :from_ids,
      options_from_collection_for_select(User.all, :id, :name),
      { prompt: 'from users',
        multiple: true,
        class: 'ui search dropdown from' } %>
  <%= select_tag :to_ids,
      options_from_collection_for_select(User.all, :id, :name),
      { prompt: 'to users',
        multiple: true,
        class: 'ui search dropdown to' } %>
  <div class="ui form">
    <%= text_field_tag :name, nil, class: 'field', placeholder: 'name' %>
  </div>
  <%= submit_tag 'Submit', class: 'submit_form' %>
<% end %>

<div class="ui modal">
  <div class="header">
    Amount
  </div>
  <div class="content">
    <div class="description">
      <div class="ui form">
        <div class="field">
          <label>Amount</label>
          <input type="number" name="amount" placeholder="Amount">
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      cancel
    </div>
    <div class="ui positive right button">
      submit
    </div>
  </div>
</div>